version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    schedule:
      interval: "weekly"

  # Enable version updates for Python (pip / requirements*.txt)
  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
    schedule:
      interval: "daily"
